# Generated by Django 3.2.9 on 2021-12-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compteTwitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=500)),
                ('nb_followers', models.IntegerField()),
                ('nb_friends', models.IntegerField()),
                ('nb_tweets', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Compte Twitter',
                'ordering': ['nb_followers'],
            },
        ),
        migrations.CreateModel(
            name='Essai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('nb_comments', models.IntegerField()),
                ('nb_rt', models.IntegerField()),
                ('nb_like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('nb_comments', models.IntegerField()),
                ('nb_rt', models.IntegerField()),
                ('nb_like', models.IntegerField()),
                ('compteTwitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.comptetwitter')),
            ],
            options={
                'verbose_name': 'Tweets',
                'ordering': ['nb_like'],
            },
        ),
    ]
