# Generated by Django 3.2.9 on 2021-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptetwitter',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comptetwitter',
            name='nb_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comptetwitter',
            name='nb_friends',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comptetwitter',
            name='nb_tweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comptetwitter',
            name='screen_name',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='nb_comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='nb_like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='nb_rt',
            field=models.IntegerField(null=True),
        ),
    ]
