# Generated by Django 3.2.9 on 2021-12-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_tweet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='id_tweet',
            field=models.IntegerField(null=True),
        ),
    ]
