# Generated by Django 3.2.9 on 2021-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_tweet_id_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptetwitter',
            name='profile_url',
            field=models.URLField(null=True),
        ),
    ]
