# Generated by Django 3.2.9 on 2021-12-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_comptetwitter_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField()),
                ('created_at', models.DateTimeField(null=True, verbose_name='Date de création du jeu')),
            ],
            options={
                'verbose_name': 'Jeux',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Essai',
        ),
        migrations.AlterModelOptions(
            name='comptetwitter',
            options={'ordering': ['created_at'], 'verbose_name': 'Compte Twitter'},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['created_at'], 'verbose_name': 'Tweets'},
        ),
        migrations.AddField(
            model_name='game',
            name='compte1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptetwitter1_content_type', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='game',
            name='compte2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptetwitter2_content_type', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='game',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tweet'),
        ),
    ]
