# Generated by Django 3.2.9 on 2021-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20211229_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='compte1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='compte2',
        ),
        migrations.AddField(
            model_name='game',
            name='comptes',
            field=models.ManyToManyField(to='game.compteTwitter'),
        ),
    ]
