# Generated by Django 3.2.9 on 2021-12-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20211229_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jeux'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
    ]
