# Generated by Django 3.2.9 on 2022-01-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_jeu_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeu',
            name='comptes',
        ),
        migrations.AddField(
            model_name='jeu',
            name='compteTwitter1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compteTwitter1', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='compteTwitter2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compteTwitter2', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Date de création du jeu'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.comptetwitter'),
        ),
    ]
