# Generated by Django 3.2.9 on 2022-01-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220103_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='compteTwitter1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT1', to='game.comptetwitter'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='compteTwitter2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT2', to='game.comptetwitter'),
        ),
    ]
