# Generated by Django 3.2.9 on 2022-01-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_jeu_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='tweet',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='game.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='compteTwitter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.comptetwitter'),
        ),
    ]
