# Generated by Django 3.2.9 on 2022-01-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20220103_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='compteTwitter1',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT1', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='compteTwitter2',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT2', to='game.comptetwitter'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='win',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT3', to='game.comptetwitter'),
        ),
    ]
