# Generated by Django 3.2.9 on 2022-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_jeu_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='win',
            field=models.BooleanField(default=1),
        ),
    ]
