# Generated by Django 3.2.9 on 2022-01-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_jeu_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='win',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT3', to='game.comptetwitter'),
        ),
    ]
