# Generated by Django 3.2.9 on 2022-01-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_jeu_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='compteTwitter1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT1', to='game.comptetwitter'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='compteTwitter2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT2', to='game.comptetwitter'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tweet'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT3', to='game.comptetwitter'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='compteTwitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.comptetwitter'),
        ),
    ]
