# Generated by Django 3.2.9 on 2022-01-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20220105_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jeu',
        ),
    ]
