# Generated by Django 3.2.9 on 2022-01-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_delete_jeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Date de création du jeu')),
                ('compteTwitter1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT1', to='game.comptetwitter')),
                ('compteTwitter2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT2', to='game.comptetwitter')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tweet')),
                ('win', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cT3', to='game.comptetwitter')),
            ],
            options={
                'verbose_name': 'Jeux',
            },
        ),
    ]
