# Generated by Django 3.2.9 on 2022-01-07 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_jeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date de création du jeu'),
        ),
    ]
