# Generated by Django 3.2.9 on 2022-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_jeu_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='type',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
